name: Deploy
on:
  workflow_dispatch:

concurrency: one-deploy-at-a-time

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/cargo-lambda/cargo-lambda@sha256:087f8506865ad5c5e905eed0eb4a86583441144367ba7bc4a95d36e789163cad
    environment: production

    steps:
      - uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-west-2
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: cargo lambda build --release && cargo lambda deploy -r us-west-2
