name: Deploy
on:
  workflow_dispatch:

concurrency: one-deploy-at-a-time

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885
        with:
          role-to-assume: ${{ secrets.role }}
          aws-region: us-west-2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: cargo lambda build --release && cargo lambda deploy -p statuspage
